spring.application.name=financial-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/finance_tracker_db
spring.datasource.username=root
spring.datasource.password=Thisara@499
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
